version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: student_grade_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_grade_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./backend
    container_name: grade_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: student_grade_db
      DB_PORT: 5432
      JWT_SECRET: supersecretkey

volumes:
  pgdata:
